---
title: "Playing around with python, Methods 3 2025"
output: pdf_document
---

```{=html}
<style type="text/css">
  body{
  font-size: 14pt;
}
</style>
```

# Exercises and objectives

1)  Get acquainted with *Python*, and learn some of the differences between it and *R*\
2)  Estimate bias and variance based on a true underlying function

REMEMBER: In your report, make sure to include code that can reproduce the answers requested in the exercises below (**MAKE A KNITTED VERSION**)\
REMEMBER: All exercises should be done in *Python*

# EXERCISE 1 Get acquainted with *Python* learn some of the differences between it and *R*

To make sure that *Python* runs within *R Markdown*, make sure you have the *reticulate* package installed `install.packages('reticulate')`

```{r}
library(reticulate)
print(conda_list())
use_condaenv('methods3_2025', required = TRUE)
```

## Good to know about *Python* (in no particular order)

```{python}
## assignment is done and only done with "=" (no arrows)
a = 2
# a <- 2 # results in a syntax error
## already assigned variables can be reassigned with basic arithmetic operations
a += 2
print(a)
a -= 1
print(a)
a *= 4
print(a)
a //= 2 # integer division
print(a)
a /= 2 # float  (numeric from R) division
print(a)
a **= 3 # exponentiation 
print(a)##

a_list = [1, 2] # initiate a list (the square brackets) with the integers 1 and 2
b = a_list ## b now points to a_list, not to a new list with the integers 1 and 2 

a_list.append(3) # add a new value to the end of the list
print(a_list)
print(b) # make sure you understand this

print(a_list[0]) # zero-indexing
print(a_list[1])


new_list = [0, 1, 2, 3, 4, 5]
print(new_list[0:3])  # slicing

for index in range(0, 5): # indentation (use tabulation) controls scope of control variables 
    #(no brackets necessary),
    if index == 0: # remember the colon
        value = 0
    else:
        value += index
    print(value)

  
this_is_true = True # logical values
this_is_false = False
    
# define functions using def
def fix_my_p_value(is_it_supposed_to_be_significant):
    if is_it_supposed_to_be_significant:
        p = 0.01
    else:
        p = 0.35
    return(p)

print(fix_my_p_value(True))


import numpy # methods of numpy can now be accessed as below
# importing packages (similar to library)

print(numpy.arange(1, 10)) # see the dot
print(numpy.abs(-3))
import numpy as np # you can import them with another name than its default
print(np.cos(np.pi))
from numpy import pi, arange # or you can import specific methods
print(arange(1, 7))
print(pi)

matrix = np.ones(shape=(5, 5)) # create a matrix of ones
identity = np.identity(5) # create an identity matrix (5x5)
identity[:, 2] = 5 # exchange everything in the second column with 5's

## no dots in names - dots indicate applying a method like the dollar sign $ in R

import matplotlib.pyplot as plt
plt.figure() # create new figure
plt.plot([1, 2], [1, 2], 'b-') # plot a blue line
# plt.show() # show figure
plt.plot([2, 1], [2, 1], 'ro') # scatter plot (red)
# plt.show()
plt.xlabel('a label')
plt.title('a title')
plt.legend(['a legend', 'another legend'])
# plt.show()
```

1)  Do a linear regression based on *x*, *X* and *y* below (*y* as the dependent variable) (Exercise 1.1)
    i.  find $\hat{\beta}$ and $\hat{y}$ (\@ is matrix multiplication)
    ii. plot a scatter plot of *x*, *y* and add a line based on $\hat{y}$ (use `plt.plot` after running `import matplotlib.pyplot as plt`)\
2)  Create a model matrix, $X$ that estimates $\hat\beta$, the means of the three sets of observations below, $y_1, y_2, y_3$ (Exercise 1.2) (i.e. an ANOVA)
    i.  find $\hat\beta$ based on this $X$\


```{python}
# Exercise 1.1
import numpy as np
np.random.seed(7) # for reproducibility

x = np.arange(10)
y = 2 * x
y = y.astype(float)
n_samples = len(y)
y += np.random.normal(loc=0, scale=1, size=n_samples)

X = np.zeros(shape=(n_samples, 2))
X[:, 0] = x ** 0
X[:, 1] = x ** 1

```

```{python}
# Exercise 1.2
y1 = np.array([3, 2, 7, 6, 9])
y2 = np.array([10, 4, 2, 1, -3])
y3 = np.array([15, -2, 0, 0, 3])
y = np.concatenate((y1, y2, y3))

```
