name: methods3_2025
channels:
- defaults
- conda-forge
dependencies:
## Python version
- python>=3.13.7

## Python packages
- pip=25.2
- scikit-learn=1.7.1
- matplotlib=3.10.5
- numpy=2.3.1
- scipy=1.16.1
- pandas=2.3.2
- seaborn=0.13.2
